@echo off
echo Starting Prompt Manager on Port 2731...
cd prompt-manager-svelte
echo Installing dependencies (if needed)...
call npm install
echo Starting Development Server...
call npm run dev -- --open
pause
